project_id = "hlywucxwpzbqmzssmwpj"

[functions.generate-story-audio]
verify_jwt = false

[functions.generate-story-pdf]
verify_jwt = false

[functions.send-story-submission-email]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.generate-speed-dial-icon]
verify_jwt = false

[functions.check-password-strength]
verify_jwt = false

[functions.auth-custom-claims]
verify_jwt = false

[functions.secure-auth]
verify_jwt = false
